### ISSUE TITLE
Create Status Endpoint

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/active_encode#48]
### Description
The system can query an endpoint that returns json about a single encode job. 
Create endpoints for transcoding within active encode. The end result will be an api that can be used in a react or other front end applicaiton
- Decide on what needs to be queried for dashboard (minimal -- started, currently encoding, possibly time remaining, and complete)
- Create endpoints for querying via front-end

### Notes
Before building a dashboard, showing the status of a single encode on a work page.
Getting rid of the Hyrax "your work is happening in the background!" info.

The dashboard may use this endpoint, or something different that returns more information.

## Done looks like

- Active encode provides endpoint that will return json status of an encode object.

**Comment by davidschober** [comment]
@cjcolvar is this in "in review" it seems stuck.
