### ISSUE TITLE
Sprockets dependency

### ISSUE THREAD

**Issue by clemensg** [samvera-labs/active_encode#82]
Hello,

I noticed that there is a dependency on sprockets < 4 in the gemspec, which blocks the update to active_encode 0.8.1 in a Rails 6 project (which uses sprockets 4).
I don't see any parts in active_encode actually using sprockets, so I would like to know why the dependency was added (the comment does not really help) and if there are any objections to removing it?

**Comment by phuongdh** [comment]
I haven't been involved with the community for a while and don't remember why sprockets is there. Feel free to submit a PR removing it.

**Comment by cjcolvar** [comment]
Fixed by #104
